# Generated by Django 2.2.2 on 2021-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question', models.TextField(max_length=100)),
                ('priority', models.CharField(choices=[('H', 'Hight'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
            ],
            options={
                'verbose_name': 'Question Types',
                'verbose_name_plural': 'Asking To admin',
            },
        ),
    ]
