# Generated by Django 3.2.4 on 2021-06-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
